### ISSUE TITLE
ModuleNotFoundError: No module named 'chainermn'

### ISSUE THREAD

**Issue by NeuralBricolage** [pfnet-research/sngan_projection#23]
for single GPU i get this error though chainermn is not a required package:

Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 67, in main
    gen, dis = load_models(config)
  File "train.py", line 38, in load_models
    gen = yaml_utils.load_model(gen_conf['fn'], gen_conf['name'], gen_conf['args'])
  File "/home/lena/sngan_projection/source/yaml_utils.py", line 45, in load_model
    model = load_module(model_fn, model_name)
  File "/home/lena/sngan_projection/source/yaml_utils.py", line 41, in load_module
    return getattr(__import__(mod_name), name)
  File "gen_models/resnet_small.py", line 4, in <module>
    from gen_models.resblocks import Block
  File "/home/lena/sngan_projection/gen_models/resblocks.py", line 5, in <module>
    from source.links.categorical_conditional_batch_normalization import CategoricalConditionalBatchNormalization
  File "/home/lena/sngan_projection/source/links/categorical_conditional_batch_normalization.py", line 13, in <module>
    from source.links.conditional_batch_normalization import ConditionalBatchNormalization
  File "/home/lena/sngan_projection/source/links/conditional_batch_normalization.py", line 14, in <module>
    from chainermn.functions.batch_normalization import \
ModuleNotFoundError: No module named 'chainermn'

for the time being i commented out the import from conditional_batch_normalization.py
#from chainermn.functions.batch_normalization import \
#    MultiNodeBatchNormalizationFunction

**Comment by takerum** [comment]
Oh sorry, thanks for letting me know that. I will fix it. The ChainerMN package is not necessarily on single GPU.
