### ISSUE TITLE
interpolation script doesn't work

### ISSUE THREAD

**Issue by jcpeterson** [pfnet-research/sngan_projection#5]
I couldn't find where the ws_z arguments etc were from, and indeed running the script gives:

```
Traceback (most recent call last):                                                                                                                  
  File "evaluations/gen_interpolated_images.py", line 82, in <module>
    main()                                                                                                                                          
  File "evaluations/gen_interpolated_images.py", line 66, in main
    x = gen(zs=noises, ys=classes, ws_z=ws_z, ws_y=ws_y)                                                                                            
TypeError: __call__() got an unexpected keyword argument 'ws_z'
```

**Comment by jcpeterson** [comment]
bump

**Comment by takerum** [comment]
The interpolation code was fixed. Please see #6.
